### ISSUE TITLE
Do you use it for Multiplayer Game? 

### ISSUE THREAD

**Issue by voody2506** [iShape-Swift/iFixBox#1]

**Comment by NailxSharipov** [comment]
Hi!
It was a plan.
But right now it's only a prototype.
You can see it at git@github.com:iShape-Swift/FixBoxApp.git

https://github.com/user-attachments/assets/52a82b83-16e7-4b44-9745-593bd74acd78

**Comment by voody2506** [comment]
Amazing. Are you plan to use GodoSwift with Rollback netcode?

**Comment by NailxSharipov** [comment]
Yes, exactly. The determinism is necessary if we wish client do all simulations alone and only sync events (not states) with server and rollback and re-simulation if necessary.
